# <center> Numpy Basics </center>

In [5]:
#import numpy module with alias np
import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
arr = np.array([1,2,3])

In [ ]:
# print output
arr

array([1, 2, 3])

## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [ ]:
#define a,b,c and d as instructed above

a = np.array([10])
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d
np.ndim(a)
np.ndim(b)
np.ndim(c)
np.ndim(d)

3

Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute

In [ ]:
from numpy.core.fromnumeric import shape
# print shape of each a,b ,c and d
shape(a)
shape(b)
shape(c)
shape(d)

(2, 2, 3)

Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
type(c)
type(d)

numpy.ndarray

Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable
type(a)
type(b)

numpy.ndarray

In [ ]:
# Lets check length of array b, using len() function
len(b)

3

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element

In [ ]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30] 
l2 = [40,50,60]
l3 = np.array([10,20,30])
l4 = np.array([40,50,60])

Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [ ]:
#code here as instructed above
l1*l2

TypeError: ignored

Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:
l3*l4

array([ 400, 1000, 1800])

Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>

In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it

np.arange(1)

array([0])

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
np.arange(1,2)

array([1])

In [ ]:
# create numpy array using eye function with 3 as passed parameter
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(start=1, stop=17)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
# Reshape x with 2 rows and 8 columns
x.reshape([2,8])

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array

In [ ]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x.reshape([2,2,4])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y= x.reshape([2,2,4])


print (y)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

In [ ]:
# Flattening y
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
# Create an array a with all even numbers between 1 to 17
a = np.array([2,4,6,8,10,12,14,16])


print(a)

[ 2  4  6  8 10 12 14 16]

In [ ]:
# Get third element in array a
a[3]

8

In [ ]:
#Print 3rd, 5th, and 7th element in array a
a[[3,5,7]]

array([ 8, 12, 16])

Lets check the same for 2 D array

In [13]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
# print the 3rd element from the 3rd row of a
a[2,2]

9

Well done!

Now lets check indexing for 3 D array

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = ([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) 
b

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

In [6]:
# Create 1D array

arr= np.array([1,2,3,4,5])

In [7]:
# Slice elements from 1st to 5th element from the following array:
arr[1:5]

array([2, 3, 4, 5])

Note: The result includes the start index, but excludes the end index.

In [8]:
# Slice elements from index 5 to the end of the array:
arr[5:]

array([], dtype=int64)

In [9]:
# Slice elements from the beginning to index 5 (not included):
arr[:4]

array([1, 2, 3, 4])

**STEP**

Use the step value to determine the step of the slicing:

In [10]:
# Print every other element from index 1 to index 7:
arr[1:7]

array([2, 3, 4, 5])

Did you see? using step you were able to get alternate elements within specified index numbers.

In [11]:
# Return every other element from the entire array arr:
arr

array([1, 2, 3, 4, 5])

well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [14]:
# Print array a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
a[2,1:5]

array([8, 9])

In [15]:
# In array 'a' print index 2 from all the elements :
a[2]

array([7, 8, 9])

In [17]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [18]:
x1= np.array([1,2,3,4,5])

In [19]:
# assign x2 = x1
x2 = x1

In [21]:
#print x1 and x2
print(x1)
print(x2)

[1 2 3 4 5]
[1 2 3 4 5]

Ok now you have seen that both of them are same

In [22]:
# change 1st element of x2 as 10
x2[0] = 10

In [23]:
#Again print x1 and x2
print(x1)
print(x2)

[10  2  3  4  5]
[10  2  3  4  5]

In [37]:
# Check memory share between x1 and x2
may_share_memory(x1,x2)

True

Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [26]:
# Create a view of x1 and store it in x3.
x1
x3 = x1

In [36]:
# Again check memory share between x1 and x3
may_share_memory(x1,x3)

True

Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [28]:
#Change 1st element of x3=100
x3[0] = 100

In [29]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   2   3   4   5]
[100   2   3   4   5]

Now its proved.

Lets see how **Copy()** function works

In [30]:
# Now create an array x4 which is copy of x1

x4= x1.copy()

In [32]:
# Change the last element of x4 as 900
x4[4] = 900

In [33]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[100   2   3   4   5]
[100   2   3   4 900]

Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [35]:
#Check memory share between x1 and x4
may_share_memory(x1,x4)

False

**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [39]:
# stack x1 and x4 along columns.
np.hstack((x1,x4))

array([100,   2,   3,   4,   5, 100,   2,   3,   4, 900])

In [38]:
#stack x1 and x4 along rows
np.vstack((x1,x4))

array([[100,   2,   3,   4,   5],
       [100,   2,   3,   4, 900]])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [44]:
arr1 = np.array([[1,2],[3,4]])


arr2 = np.array([[7,8],[10,16]])


##join arr1 and arr2 along rows using concatenate() function
np.concatenate((arr1,arr2),axis = 0 )

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [10, 16]])

In [45]:
##join arr1 and arr2 along columns using concatenate() function
np.concatenate((arr2,arr1),axis = 1 )

array([[ 7,  8,  1,  2],
       [10, 16,  3,  4]])

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [47]:
# append arr2 to arr1
np.append(arr2,arr1)

array([ 7,  8, 10, 16,  1,  2,  3,  4])

Lets use insert() function which Inserts values into array before specified index value

In [49]:
# Inserts values into array x1 before index 4 with elements of x4
np.insert(x1,4,[4])

array([100,   2,   3,   4,   4,   5])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [50]:
# delete 2nd element from array x2
np.delete(x2,2)

array([100,   2,   4,   5])

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!